### ISSUE TITLE
NoClassDefFoundError: com/vdurmont/emoji/EmojiParser$FitzpatrickAction

### ISSUE THREAD

**Issue by fuuqiu** [vdurmont/emoji-java#170]
`        <dependency>
            <groupId>cn.hutool</groupId>
            <artifactId>hutool-all</artifactId>
            <version>5.5.4</version>
        </dependency>
`

`
Exception in thread "main" java.lang.NoClassDefFoundError: com/vdurmont/emoji/EmojiParser$FitzpatrickAction
	at cn.hutool.extra.emoji.EmojiUtil.toAlias(EmojiUtil.java:104)
	at com.ruoyi.web.controller.common.CaptchaController.main(CaptchaController.java:90)
Caused by: java.lang.ClassNotFoundException: com.vdurmont.emoji.EmojiParser$FitzpatrickAction
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 2 more
`

**Comment by baszero** [comment]
Then you don't have the emoji lib on your runtime class path. please close this issue. @sullis
